### LAB 2: NUMPY, PANDAS VÀ MATPLOTLIB NÂNG CAOCAO

### 1. NUMPY

In [4]:
import numpy as np

x = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
#Lấy số 3
x[2]

#Lấy 1 2 3 
x[:3]

#Lấy từ 3 - 8
x[2:8]

x[2:]

#Lấy từ 3 -> 7
x[2:7]

x[2:-1]

#Lấy 7, 8
x[-2:]

#Lấy phần tử với index 2 và 4
x [2], x[4]

data = ([1,2], [3,4], [5,6])
mang = np.array(data)
print(mang)


mang [0,1]
mang [-1,1]

#Lấy 3 4 5 6
mang[1:, :]

#cách 2
mang [[1,2], :]

mang [1:3]

mang [[1, 1, 2, 2, 2]]

result = x[[-1, -2, -3, -4]]
print(result)

[[1 2]
 [3 4]
 [5 6]]
[16 15 14 13]


### BÀI TẬP TẾT VỀ NHÀ 

# Cho ma trân sau = [ 
#       [99,99,99],
#       [99,99,99],
#       [99,99,99]
# ]

# Giả sử 0 = 0 và 1 là x
# Nhận đầu vào từ phía x và 0 luân phiên 
# cho các bạn một cặp chỉ số
# nếu phía x nhập ((0,0)) thì ma trận trở thành 
# [ 
#       [XX,99,99],
#       [99,99,99],
#       [99,99,99]
# ]

# Nếu phía 0 nhập ((0,0)) thì yếu cầu nhập lại và nếu không thì điền vào ma trận 

# Thử thách của các bạn ở nhà ăn tết: nếu ai đó có ba ô liên tiếp thì dừng trò chơi.



### Bài tập trên lớp từ 14h20p - 14h35

# Cho ma trận sau 
matrix = [ 
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

# Câu 1: Lấy 4, 5, 6
result1 = matrix[1]
print("Câu 1:", result1)
# Câu 2: Lấy 2, 5
result2 = [matrix[0][1], matrix[1][1]]
print("Câu 2:", result2)
# Câu 3: Lấy 3, 4
result3 = [matrix[0][2], matrix[1][0]]
print("Câu 3:", result3) 
# Câu 4: Lấy 9, 6, 3
result4 = [matrix[2][2], matrix[1][2], matrix[0][2]]
print("Câu 4:", result4)

In [5]:
#Cho ma trận sau:
matran = [ 
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

# Câu 1: Lấy 4, 5, 6
result1 = matran[1]
print("Câu 1:", result1)
# Câu 2: Lấy 2, 5
result2 = [matran[0][1], matran[1][1]]
print("Câu 2:", result2)
# Câu 3: Lấy 3, 4
result3 = [matran[0][2], matran[1][0]]
print("Câu 3:", result3) 
# Câu 4: Lấy 9, 6, 3
result4 = [matran[2][2], matran[1][2], matran[0][2]]
print("Câu 4:", result4)

Câu 1: [4, 5, 6]
Câu 2: [2, 5]
Câu 3: [3, 4]
Câu 4: [9, 6, 3]


In [6]:
#Cho ma trận sau:
matran = [ 
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

matrix_np = np.array(matran)
# Câu 1: Lấy 4, 5, 6
result1_np = matrix_np[1,:]
print("Câu 1:", result1)
# Câu 2: Lấy 2, 5
result2_np = matrix_np[[0,1], [1,1]]
print("Câu 2:", result2)
# Câu 3: Lấy 3, 4
result3_np = [matrix_np[0,2], matrix_np[1,0]]
print("Câu 3:", result3) 
# Câu 4: Lấy 9, 6, 3
result4_np = matrix_np[::-1, 2]
print("Câu 4:", result4)

Câu 1: [4, 5, 6]
Câu 2: [2, 5]
Câu 3: [3, 4]
Câu 4: [9, 6, 3]


In [9]:
import numpy as np

# Tạo ma trận từ dữ liệu cho trước
Matran = [[1, 2, 3], 
          [4, 5, 6], 
          [7, 8, 9]]
mang = np.array(Matran)

# Lấy 4, 5, 6 (hàng 1)
print(mang[1,:])  # [4 5 6]

# Lấy 2, 5 
print(mang[0,1], mang[1,1])  # 2 5

# Lấy 3, 4
print(mang[0,2], mang[1,0])  # 3 4

# Lấy 9, 6, 3 
print(mang[2,2], mang[1,2], mang[0,2])  # 9 6 3

[4 5 6]
2 5
3 4
9 6 3


In [11]:
import pandas as pd
x = [1,2,3,4,5,6,7,8,9,10]

series = pd.Series(x)
# Lấy ra các phần tử có số chẵn
even1 = series[series % 2 == 0]
print("Cách 1:")
print(even1)

even3 = series.loc[series % 2 == 0]
print("\nCách 2:")
print(even3)



Cách 1:
1     2
3     4
5     6
7     8
9    10
dtype: int64

Cách 2:
1     2
3     4
5     6
7     8
9    10
dtype: int64


In [14]:
x = [1,2,3,4,5,6,7,8,9,10]
#Lấy chẵn
mang_chan = [ num for num in x if num % 2== 0]
print(mang_chan)
#Lấy lẻ
mang_le = [ num for num in x if num % 2== 1]
print(mang_le)

[2, 4, 6, 8, 10]
[1, 3, 5, 7, 9]


In [15]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.arange (3)

array([0, 1, 2])

In [24]:
np.ones((3,3)) + np.arange (3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [26]:
x = np.arange (3)
x

array([0, 1, 2])

In [27]:
x.shape 

(3,)

In [28]:
x = x.reshape((3,1))
x

array([[0],
       [1],
       [2]])

In [30]:
y = np.arange(3)
y

array([0, 1, 2])

In [ ]:
y = np.arange(3)
y

In [31]:
x + y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

### BÀI TẬP KẾT NUMPY
# Tạo 1 mảng numpy có kích thước 150 x 5 hãy tưởng tượng mảng này chứa 150 mẫu về chiều cao, cân năng, tuổi, lương, GPA của sinh viên Văn Lang

# Chia mảng bốn cột đầu tiên thành một biến có tên là X và cột cuối cùng thành Y.

# Chia X thành X_train và X_test chứa 70% dữ liệu và chia y thành y_train và y_test, trong đó y_train chứa 70% dữ liệu.

# Tạo 10 tập dữ liệu không chồng chéo của X_train.

In [26]:
import numpy as np
data = np.random.uniform(0, 10, (150, 5))
data.shape

(150, 5)

In [27]:
x = data[:, :-1] 
y = data[:, -1]

x.shape, y.shape

((150, 4), (150,))

In [28]:
dataset_size  = x.shape[0]
dataset_size



150

In [29]:
train_size = int(dataset_size * 0.7)
train_size

105

In [30]:
x_train = x[:train_size]
x_test = x[train_size:]

x_train.shape, x_test.shape

((105, 4), (45, 4))

In [31]:
split = x_train.shape[0]//10
split


10

In [32]:
for counter in range(0, x_train.shape[0], split):
    print(x_train[counter:counter+split].shape)

(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(10, 4)
(5, 4)
